import app from './js/app';

import './css/fonts.css';
import './css/reset.css';
import './css/style.css';
import './css/slider-coffee.css';
import './css/slider-head.css';
import './css/mixin-title-for-section.css';
import './css/mixin-navigation.css';
import './css/slider-perspective.css';
import './css/logo.css';
import './css/arrows.css';
import './css/mixin-navigation-mobile.css';
import './css/layout.css';
import './css/about-us.css';
import './css/service.css';
import './css/delivery.css';
import './css/price.css';
import './css/change-password.css';
import './css/account.css';
import './css/basket.css';
import './css/place-an-order.css';
import './css/__modals.css';
import 'air-datepicker/air-datepicker.css';